version: "3.4"

services:
  database_postgres:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
volumes:
  portainer_data:
  pgdata:
